version: "3"

services:
    geth01.mynode.com:
        image: geth
        tty: true
        ports:
            - 8545:8545
            - 30305:30305
        container_name: geth01.mynode.com
        command: /bin/bash -c "geth --datadir /home/ethereum init /home/ethereum/genesis.json && geth --datadir /home/ethereum --nodiscover --allow-insecure-unlock --maxpeers 30 --http --http.port 8545 --http.addr '0.0.0.0' --http.corsdomain '*' --http.api 'admin,eth,debug,miner,net,txpool,personal,web3' --port 30305"
        working_dir: /home/ethereum
        
    geth02.mynode.com:
        image: geth
        tty: true
        ports:
            - 8546:8546
            - 30306:30306
        container_name: geth02.mynode.com
        command: /bin/bash -c "geth --datadir /home/ethereum init /home/ethereum/genesis.json && geth --datadir /home/ethereum --nodiscover --allow-insecure-unlock --maxpeers 30 --http --http.port 8546 --http.addr '0.0.0.0' --http.corsdomain '*' --http.api 'admin,eth,debug,miner,net,txpool,personal,web3' --port 30306"
        working_dir: /home/ethereum

    geth03.mynode.com:
        image: geth
        tty: true
        ports:
            - 8547:8547
            - 30307:30307
        container_name: geth03.mynode.com
        command: /bin/bash -c "geth --datadir /home/ethereum init /home/ethereum/genesis.json && geth --datadir /home/ethereum --nodiscover --allow-insecure-unlock --maxpeers 30 --http --http.port 8547 --http.addr '0.0.0.0' --http.corsdomain '*' --http.api 'admin,eth,debug,miner,net,txpool,personal,web3' --port 30307"
        working_dir: /home/ethereum      