version: "3"

services:
    geth:
        image: geth
        tty: true
        ports:
            - 8545:8545
            - 30303:30303
        container_name: geth
        command: /bin/bash -c "geth --datadir /home/ethereum init /home/ethereum/genesis.json && geth --datadir /home/ethereum --nodiscover --allow-insecure-unlock --maxpeers 30 --http --http.port 8545 --http.addr '0.0.0.0' --http.corsdomain '*' --http.api 'admin,eth,debug,miner,net,txpool,personal,web3' --port 30303"
        working_dir: /home/ethereum
