version: "3"

networks:
  private:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

services:
  geth01.mynode.com:
    image: geth
    tty: true
    networks:
      private:
        ipv4_address: 172.20.0.2
    ports:
      - 8545:8545
      - 30305:30305
    container_name: geth01
    command: /bin/bash -c "geth --datadir /home/ethereum init /home/ethereum/genesis.json && geth --datadir /home/ethereum --nodiscover --allow-insecure-unlock --maxpeers 30 --http --http.port 8545 --http.addr '0.0.0.0' --http.corsdomain '*' --http.api 'admin,eth,debug,miner,net,txpool,personal,web3' --port 30305"
    working_dir: /home/ethereum

  geth02.mynode.com:
    image: geth
    tty: true
    networks:
      private:
        ipv4_address: 172.20.0.3
    ports:
      - 8546:8545
      - 30306:30305
    container_name: geth02
    command: /bin/bash -c "geth --datadir /home/ethereum init /home/ethereum/genesis.json && geth --datadir /home/ethereum --nodiscover --allow-insecure-unlock --maxpeers 30 --http --http.port 8545 --http.addr '0.0.0.0' --http.corsdomain '*' --http.api 'admin,eth,debug,miner,net,txpool,personal,web3' --port 30305"
    working_dir: /home/ethereum
