CONFIG_NAME: "prysm-private"
PRESET_BASE: "mainnet"

# Genesis
GENESIS_DELAY: 10
MIN_GENESIS_TIME: 0
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 1
GENESIS_FORK_VERSION: 0x10000001

# Altair
ALTAIR_FORK_EPOCH: 0
ALTAIR_FORK_VERSION: 0x20000001

# Bellatrix (Merge)
BELLATRIX_FORK_EPOCH: 0
BELLATRIX_FORK_VERSION: 0x30000001
TERMINAL_TOTAL_DIFFICULTY: 0
TERMINAL_BLOCK_HASH: 0x908bce4135767e43c0ae160fe599eb0f7a78d23410e859325cb069df376f01bc
TERMINAL_BLOCK_HASH_ACTIVATION_EPOCH: 0

# Capella
CAPELLA_FORK_EPOCH: 0
CAPELLA_FORK_VERSION: 0x40000001

# Deneb
DENEB_FORK_EPOCH: 0
DENEB_FORK_VERSION: 0x50000001

# Electra
ELECTRA_FORK_EPOCH: 0
ELECTRA_FORK_VERSION: 0x60000001

# Fulu
FULU_FORK_EPOCH: 0
FULU_FORK_VERSION: 0x70000001

# Time parameters
SECONDS_PER_SLOT: 12
SLOTS_PER_EPOCH: 32
EPOCHS_PER_ETH1_VOTING_PERIOD: 64

# Deposit contract
DEPOSIT_CHAIN_ID: 32382
DEPOSIT_NETWORK_ID: 32382
DEPOSIT_CONTRACT_ADDRESS: 0x4242424242424242424242424242424242424242
